### PR TITLE
electrum_server: set logging format

### PR DESCRIPTION
**Pull request by romanz**
`'%(asctime)s %(levelname)-12s %(message)-100s [%(filename)s:%(lineno)d]'`

### CODE REVIEW

**Comment by kyuupichan** [comment]
Example output and rationale of why it's an improvement would be nice.  For example, I get timestamps already from multilog

**Comment by kyuupichan** [comment]
Does this truncate backtraces?

**Comment by romanz** [comment]
Example log output (using the suggested format):
```
2018-03-06 16:08:18,921 INFO         ElectrumX server starting                                                                            [electrumx_server.py:24]
2018-03-06 16:08:18,922 WARNING      lowered maximum sessions from 1,000 to 674 because your open file limit is 1,024                     [util.py:60]
2018-03-06 16:08:18,922 INFO         event loop policy: None                                                                              [server_base.py:57]
2018-03-06 16:08:18,922 INFO         daemon #1 at localhost:8332/ (current)                                                               [daemon.py:75]
2018-03-06 16:08:18,923 INFO         switching current directory to /home/roman/.bitcoin/electrumx/db                                     [db.py:57]
2018-03-06 16:08:18,951 INFO         using leveldb for DB backend                                                                         [db.py:61]
2018-03-06 16:08:19,043 INFO         opened DB for serving                                                                                [db.py:103]
2018-03-06 16:08:19,044 INFO         software version: ElectrumX 1.2.1                                                                    [db.py:133]
2018-03-06 16:08:19,044 INFO         DB version: 6                                                                                        [db.py:134]
2018-03-06 16:08:19,044 INFO         coin: BitcoinSegwit                                                                                  [db.py:135]
2018-03-06 16:08:19,044 INFO         network: mainnet                                                                                     [db.py:136]
2018-03-06 16:08:19,044 INFO         height: 512,271                                                                                      [db.py:137]
2018-03-06 16:08:19,044 INFO         tip: 0000000000000000001cf03a79c68dd70d954f2370f48a93e68024eb3a0ecbc3                                [db.py:138]
2018-03-06 16:08:19,044 INFO         tx count: 303,138,749                                                                                [db.py:139]
2018-03-06 16:08:19,044 INFO         flush count: 1,660                                                                                   [db.py:140]
2018-03-06 16:08:19,131 INFO         deleted 146 stale undo entries                                                                       [db.py:299]
2018-03-06 16:08:19,131 INFO         reorg limit is 200 blocks                                                                            [db.py:71]
2018-03-06 16:08:19,147 INFO         RPC server listening on localhost:8000                                                               [controller.py:241]
2018-03-06 16:08:19,150 ERROR        connection problem - is your daemon running?  Retrying occasionally...                               [daemon.py:123]
^C2018-03-06 16:08:22,491 WARNING      received SIGINT signal, initiating shutdown                                                          [server_base.py:95]
2018-03-06 16:08:22,492 INFO         shutting down                                                                                        [server_base.py:78]
2018-03-06 16:08:22,492 INFO         closing down RPC listening servers                                                                   [controller.py:222]
2018-03-06 16:08:22,595 INFO         shutdown complete                                                                                    [server_base.py:90]
2018-03-06 16:08:22,595 INFO         ElectrumX server terminated normally                                                                 [electrumx_server.py:32]
```
The main reason for this PR is to add filenames and line numbers at the log (so searching for a specific log message would be easier). I agree that time-stamping can be done by an external tool.

> Does this truncate backtraces?

Do you mean exception backtraces?
IIUC, this config should not truncate those...

**Comment by kyuupichan** [comment]
OK I'm happy to give this a go.  I hope others chime in on if they consider it an improvement.  Can you do two things please:

a) the status column is too wide.  I think  CRITICAL is the longest it can be so please lower from 12 to 9 which gives room for a space.
b) Remove the "t " from contrib/daemontools/log/run which did multilog timestamping

**Comment by kyuupichan** [comment]
This seems to have lost the information about the logger - such as Mempool: that used to appear.  Has it also lost session IDs?  Those are critical for seeing what's going on.

**Comment by romanz** [comment]
Thanks, Neil!
I pushed the changes for (a), (b) and added the logger's name -> see [example log](https://gist.githubusercontent.com/romanz/d7ddaf6812d1ccad8c8a13004d70222a/raw/b445dcf7b145698d4f400ba1b466f83ec5b5de13/logger+session).

IIUC, it should keep the session IDs (tested with local Electrum instance - see the log above).

**Comment by kyuupichan** [comment]
Yes thanks.  Given you provide the file location the logger name may not be so useful any more.  I may remove it in future.  But the session IDs are very important as you need them for the local RPC client.

**Comment by shsmith** [comment]
With this change we not get double timestamps in systemd journals. I understand this is helpful in other situations. Maybe we need an environment to control the logging format.

**Comment by kyuupichan** [comment]
@shsmith @bauerj OK, this seems controversial.  I've reverted this, and introduced a LOG_FORMAT environment variable so @romanz can override to his preferred style

**Comment by shsmith** [comment]
Perfect. Thanks!

**Pull request merged**
