### PR TITLE
Support for Minexcoin

### PR DESCRIPTION
**Pull request by joesixpack**

### CODE REVIEW

**Comment by kyuupichan** [comment]
This needs a test like other new coins

**Comment by joesixpack** [comment]
Can be tested with https://github.com/racquemis/electrum-mnx
Been running for a half a year without apparent issues.

**Comment by kyuupichan** [comment]
I won't merge it without tests. See other recently added coins

**Comment by kyuupichan** [comment]
Thanks.  Can you add a changlog.rst entry too, and I'll merge it

**Pull request merged**
