### PR TITLE
Add Crown

### PR DESCRIPTION
**Pull request by Extrememist**
Crown addition

### CODE REVIEW

**Comment by kyuupichan** [comment]
Doesn't even parse.

**Comment by Extrememist** [comment]
haha yea, i just noticed that wow what'd my editor do, Ill fix the pr ;) Sorry about that haha

**Comment by Extrememist** [comment]
Sorry about that, Looks like i've fixed it i didn't notice that CoinAuxPow got switched to AuxPowMixin, Coin :)

**Comment by Extrememist** [comment]
Decided to test it locally to make sure i didn't give you broken code it works flawlessly :)

**Pull request merged**
