### PR TITLE
NIX Sigma implementation

### PR DESCRIPTION
**Pull request by phamels**
Custom deserializer for NIX with support for Sigma

### CODE REVIEW

**Comment by kyuupichan** [comment]
Testcase?

**Comment by phamels** [comment]
Tests are already in place as NIX was already added to Electrumx but this is a modification to the previous implementation.

**Comment by kyuupichan** [comment]
You've changed to a new serializer.  Any old tests can't be testing that otherwise they would presumably have failed?

**Comment by phamels** [comment]
Only test implemented is a block test which is still valid for the block it was testing

**Comment by kyuupichan** [comment]
What I'm saying is you've changed code.  You have no tests the change is good.

**Pull request closed without merging**
