### PR TITLE
Added Ritocoin

### PR DESCRIPTION
**Pull request by traysi**
This PR adds support for Ritocoin and the X21S hashing algorithm.

### CODE REVIEW

**Comment by kyuupichan** [comment]
Please update you code so pycodestyle passes on lib/coins.py (see the .travis.yml file).  For some reason github didn't run the checks; your change would fail them.

**Comment by traysi** [comment]
Hi, thank you. I updated the code and it passes pycodestyle now.

**Comment by kyuupichan** [comment]
Oops it conflicts with another merge now

**Comment by traysi** [comment]
I corrected the conflict and it should be clean now.

**Comment by ddude1** [comment]
https://github.com/RitoProject/x21s_hash  --> this is breaking the build

**Comment by streetcrypto7** [comment]
@ddude1 This PR will fix the build error https://github.com/RitoProject/x21s_hash/pull/2

Fixed test: https://travis-ci.org/streetcrypto7/electrumx/jobs/551094944

**Comment by kyuupichan** [comment]
Not sure what happened there; Travis indicated it was fine.  I've reverted it for now.

**Comment by traysi** [comment]
Strange that x21s_hash as it was before builds fine for me with python 3.7. I have merged @streetcrypto7 streetcrypto7 's PR and that should resolve the build problems that @ddude1 was experiencing.

**Pull request merged**
