### PR TITLE
Add support for ODIN Coin

### PR DESCRIPTION
**Pull request by Manbearpixel**
Thanks for your work thus far on ElectrumX! I'd like to request support for adding ODIN Blockchain onto ElectrumX. We're launching mobile wallets and are currently using your implementation for these lightweight clients.

### CODE REVIEW

**Comment by kyuupichan** [comment]
Thanks - can you fix the failure?  I use pycodestyle and it wants 2 line breaks between top-level class definitions.

**Comment by Manbearpixel** [comment]
@kyuupichan Should be all fixed up now, thanks for your quick response!

**Comment by kyuupichan** [comment]
The test you added is failing

**Comment by Manbearpixel** [comment]
@kyuupichan Figured out the issue. Must have misunderstood what was needed for the test cases.

**Pull request merged**
