### PR TITLE
Add Hush support, part deux

### PR DESCRIPTION
**Pull request by leto**
This is an updated version of https://github.com/kyuupichan/electrumx/pull/297, which I rebased from the latest master to get the Emercoin changes, and then added some tests for normal and P2SH Hush addresses. Please let me know if you would like other types of tests :metal:

### CODE REVIEW

**Comment by ingamx** [comment]
Tests passing . Nice leto

**Comment by kyuupichan** [comment]
The coverage report for lib/coins.py does not show the 2 functions in Hush class being tested at all; that is my main concern.  

https://coveralls.io/builds/14158493/source?filename=lib%2Fcoins.py

**Comment by leto** [comment]
@kyuupichan after submitting my PR, I found the test data files for each chain, and I added one for Hush. At first I thought it was just the output of `hush-cli getblock` but then I realized it was the output of the ElectrumX RPC, since it contains the `block` header that our normal JSON does not contain, i.e. the deserialized data. I am currently trying to get valid test JSON data, and will update this PR when I have that working.

FYI, the 2 functions I added are exactly the same as the Zcash functions, Hush did not change any of that. I was thinking of maybe making a Mixin, but didn't want to change too much. Do you have thoughts on that?

**Comment by leto** [comment]
@kyuupichan I have been digging deep, but I do not know how to generate the `block` key in the test data for each coin listed here: https://github.com/kyuupichan/electrumx/tree/master/tests/blocks

I have almost-correct test data here: https://github.com/leto/electrumx/blob/hush/tests/blocks/hush_mainnet_420.json but my `block` data in invalid and causes test failures.

I don't see any ElectrumX RPC method that returns the exact JSON in the test data files, can you throw me a 🍖 ? If I need to hand-carve it, any documentation about that would be appreciated.

**Comment by kyuupichan** [comment]
Testing the header function is easy - just pass it the raw 140 binary bytes of a header and assert the result is what you expect.
Similarly the other function takes the binary bytes of a block - you have one in your test already but it's a hex string rather than binary bytes - and returns the header as binary bytes.  That header can be passed into the first function.  That way you're testing both at once.

**Comment by ingamx** [comment]
how sweet 👍

**Comment by erasmospunk** [comment]
@leto please use the new `EquihashMixin` to remove duplicate code (be sure to `git rebase` to the latest master)

Check commit https://github.com/kyuupichan/electrumx/commit/f3fea9f8ee88305aa087bb996a3d1857708b3a20 that added support to `EquihashMixin`.

**Comment by erasmospunk** [comment]
@leto Also regarding the test json file, just use the `getblockhash` and `getblock` to get the decomposed block from the daemon. Remove any extra fields that you don't see in other coins and call `getblock` with an additional `false` argument to get the raw block and add it to the `"block"` field.

**Comment by leto** [comment]
This was redone in https://github.com/kyuupichan/electrumx/pull/319, closing this

**Pull request closed without merging**
