### PR TITLE
add AXE support

### PR DESCRIPTION
**Pull request by charlesrocket**
new class

### CODE REVIEW

**Comment by kyuupichan** [comment]
Are you going the new class route?  

Can you:

1) Please put 2 blank lines before class declarations, not 1
2) inherit the Dash classes and do not redefine functions that are the same.

If 2) means the classes just have a body of "pass" that is fine, but you should expect that if they remain the same for an extended time I will merge them at some point.

Please update with those changes.

**Comment by charlesrocket** [comment]
i woud like to keep new classes if its ok, will merge by your request later if needed

**Comment by charlesrocket** [comment]
working on 3.7 resolution, don't want to change travis file

**Comment by charlesrocket** [comment]
can not fix the issue with p3.7 at this time, will wait until official release. so moved classes

**Pull request merged**
