### PR TITLE
Add fujicoin

### PR DESCRIPTION
**Pull request by fujicoin**
Hi kyuupichan,

Please add fujicoin.
Only 2 files should be merged.
lib/coins.py
server/daemon.py

Electrum-X-FJC has confirmed stable operation for one month.
If you do not mind, please try using fujicoin's electrum wallet.
http://www.fujicoin.org/downloads.php

Thanks,
motty

### CODE REVIEW

**Comment by kyuupichan** [comment]
If you want this to be merged, limit it to what should be merged, not a bunch of other changes.  And explain as a comment for each new Daemon function why it needs to be overridden.  Finally add a test for the new daemon functionality.

**Comment by fujicoin** [comment]
Hi kyuupichan,

Thank you for your advice.

The only thing to merge is lib/coins.py and server/daemon.py.
Please ignore others.
I overwrote Daemon and made FujiDaemon because fujicoin's daemon has no "estimatefee" command.
This is the only change of Daemon.
FujiDaemon's Estimatefee() function is just a function that returns "0.001".
Do I need to create a test?

Thanks,
motty

**Comment by fujicoin** [comment]
Hi kyuupichan,

I added an explanation.
I do not have a response, but are you considering something?

Thanks,
motty

**Comment by bauerj** [comment]
Can you remove all the changes from this PR except for the ones you want merged?

Your donation address should certainly not be part of electrumx.

**Comment by fujicoin** [comment]
I created a new PR, so I close this PR.

**Pull request closed without merging**
