### PR TITLE
Add Vitae Support

### PR DESCRIPTION
**Pull request by akshaynexus**

### CODE REVIEW

**Comment by akshaynexus** [comment]
image
Tested and working

**Comment by kyuupichan** [comment]
Please remove electrum_header; it is dead code.  Also add block tests like other coins

**Comment by akshaynexus** [comment]
Ok,but how would i parse the header extras then?

**Comment by kyuupichan** [comment]
I don't understand the question.  That function is not used; it was for returning stuff to the client, but the RPC call no longer exists.

**Comment by akshaynexus** [comment]
Oh ok,thanks,will do the necessary changes today

**Pull request closed without merging**
