### PR TITLE
Add @lukechilds Bitcoin peers

### PR DESCRIPTION
**Pull request by lukechilds**

### CODE REVIEW

**Comment by kyuupichan** [comment]
Why?  Yours will be picked up by peer discovery; unless some of the existing ones are offline I see no reason to change the list

**Comment by lukechilds** [comment]
Ah ok, no need then.

**Comment by lukechilds** [comment]
@kyuupichan my server's been up for over a week now but I'm oretty sure no one else is connecting to me.

I can connect fine from my personal wallet and see this in the logs:

```
INFO:ElectrumX:[61] SSL 1.46.197.117:14047, 0 total
```

That's my IP, shouldn't `0 total` be higher if other people are connected to me?

I only have ports 50001/50002 open, is that all that's needed for peer discovery or do I need to allow something else?

Grepping the logs for `PeerManager` shows lots of peer connection attempts that don't appear to succeed.

```
lukechilds@bitcoin:~$ docker-compose logs electrumx | tail -n 100 | grep PeerManager
electrumx_1  | INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
electrumx_1  | INFO:PeerManager:no proxy detected, will try later
electrumx_1  | INFO:PeerManager:blacklist from https://electrum.org/blacklist.json has 605 entries
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50001 TCP] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:forgetting unreachable peer: 2a03:4000:36:29a:b8f4:38ff:fe1f:becc
electrumx_1  | INFO:PeerManager:accepted new peer 2a03:4000:36:29a:b8f4:38ff:fe1f:becc from v22019051929289916.bestsrv.de
electrumx_1  | INFO:PeerManager:accepted new peer 2a02:c207:3003:8337::1 from v22019051929289916.bestsrv.de
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50001 TCP] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a02:c207:3003:8337::1:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[v22019051929289916.bestsrv.de:50002 SSL] verified in 1.2s
electrumx_1  | INFO:PeerManager:[dxm.no-ip.biz:50002 SSL] verified in 1.8s
electrumx_1  | INFO:PeerManager:[btcnode.ddns.net:50002 SSL] verified in 1.3s
electrumx_1  | INFO:PeerManager:blacklist from https://electrum.org/blacklist.json has 605 entries
electrumx_1  | INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
electrumx_1  | INFO:PeerManager:no proxy detected, will try later
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50001 TCP] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a02:c207:3003:8337::1:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[currentlane.lovebitco.in:50002 SSL] [Errno 110] Connect call failed ('88.198.91.74', 50002)
electrumx_1  | INFO:PeerManager:[currentlane.lovebitco.in:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[currentlane.lovebitco.in:50001 TCP] [Errno 110] Connect call failed ('88.198.91.74', 50001)
electrumx_1  | INFO:PeerManager:[currentlane.lovebitco.in:50001 TCP] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:forgetting unreachable peer: currentlane.lovebitco.in
electrumx_1  | INFO:PeerManager:blacklist from https://electrum.org/blacklist.json has 605 entries
electrumx_1  | INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
electrumx_1  | INFO:PeerManager:no proxy detected, will try later
electrumx_1  | INFO:PeerManager:blacklist from https://electrum.org/blacklist.json has 605 entries
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:[2a03:4000:36:29a:b8f4:38ff:fe1f:becc:50001 TCP] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:forgetting unreachable peer: 2a03:4000:36:29a:b8f4:38ff:fe1f:becc
electrumx_1  | INFO:PeerManager:[2a02:c207:3003:8337::1:50002 SSL] [Errno 99] Address not available
electrumx_1  | INFO:PeerManager:forgetting unreachable peer: 2a02:c207:3003:8337::1
```

Is this behaviour normal or is something wrong? Any ideas?

**Comment by kyuupichan** [comment]
Did you get this sorted?  I suspect your SERVICES or REPORT_SERVICES is not right.

**Comment by kyuupichan** [comment]
Read the logs at startup

**Comment by lukechilds** [comment]
@kyuupichan thanks for the response.

I have:

```
SERVICES=tcp://:50001,ssl://:50002,wss://:50004,rpc://0.0.0.0:8000
```

`REPORT_SERVICES` is unset, looks like that is the problem, was not aware of that, just read: https://electrumx.readthedocs.io/en/latest/environment.html#envvar-REPORT_SERVICES

Can I set `REPORT_SERVICES` as both my clearnet domain and Tor hidden service domain? Docs are a little confusing unclear on this.

>Read the logs at startup

Logs at startup:

```
lukechilds@bitcoin:~$ docker-compose logs electrumx | grep PeerManager | head
electrumx_1  | INFO:PeerManager:peer discovery: ON
electrumx_1  | INFO:PeerManager:announce ourself: True
electrumx_1  | INFO:PeerManager:my clearnet self: None
electrumx_1  | INFO:PeerManager:force use of proxy: False
electrumx_1  | INFO:PeerManager:beginning peer discovery...
electrumx_1  | INFO:PeerManager:trying to detect proxy on "localhost" ports [9050, 9150, 1080]
electrumx_1  | INFO:PeerManager:accepted new peer E-X.not.fyi from coins.py
electrumx_1  | INFO:PeerManager:accepted new peer electrum.vom-stausee.de from coins.py
electrumx_1  | INFO:PeerManager:accepted new peer electrum.hsmiths.com from coins.py
electrumx_1  | INFO:PeerManager:accepted new peer helicarrier.bauerj.eu from coins.py
```

**Pull request closed without merging**
