### PR TITLE
Add Fujicoin

### PR DESCRIPTION
**Pull request by fujicoin**
Hi bauerj,

I redoed the fork and made a new pull request.
I think that it was hard to understand because the time before fork was old.

Thanks,
motty

### CODE REVIEW

**Comment by bauerj** [comment]
Thanks that looks a lot better! Do you know why FujiCoin has no concept of dynamic minimum fees (or why it doesn't provide the RPC calls)?

**Comment by fujicoin** [comment]
The release of Fujicoin is June 2014.
I think that the version of BTC-core of the forked coin is old.

**Comment by fujicoin** [comment]
In coins using the old btc-core, if "Use dynamic fees" is used in electrum, the fee will not return from electrum-X, so the user can not remit money.
This is a problem also occurring in monacoin.
Other old coins are probably the same.
I think that there is the idea that this problem should be handled by the application side including electrum.
What shall we do?

**Comment by kyuupichan** [comment]
This is fine.  Can you please add a comment to that effect to the implementation code, so anyone reading it understands why it is there.  Then I'll merge.

**Comment by fujicoin** [comment]
Hi kyuupichan,

I add explanation of FujiDaemon.

Thanks,
motty

**Pull request merged**
