### PR TITLE
Pivx support

### PR DESCRIPTION
**Pull request by erasmospunk**

### CODE REVIEW

**Comment by erasmospunk** [comment]
After rebasing to the latest version it broke due to the new mempool code. Will re-upload with a fix.

**Comment by kyuupichan** [comment]
There's nothing here that's memo dependent. Travis is flaky and falling arbitrarily recently. I think this was one of those?

**Comment by erasmospunk** [comment]
No, the problem was the zerocoin transactions that have coinbase-like inputs.

**Comment by erasmospunk** [comment]
Anyway, I will try to fix it in a new PR.

**Comment by kyuupichan** [comment]
OK - no tests failed, so if something is wrong I guess a new test is needed!

**Pull request merged**
