### PR TITLE
Namecoin: Support indexing name scripts

### PR DESCRIPTION
**Pull request by JeremyRand**
Since the functionality discussed in https://github.com/kyuupichan/electrumx/issues/587 is not yet implemented, this PR enables indexing of name scripts (both by the address-determining part of the script and the name part of the script).  I've tested it with the master branch of Electrum-NMC.

### CODE REVIEW

**Comment by JeremyRand** [comment]
Sorry about the Travis fail, I'll fix that ASAP

**Comment by kyuupichan** [comment]
Hi Jeremy,

Can you add some tests that give at least 60% coverage of the new processing code in coins.py?  I may need to refactor this or other parts of ElectrumX in the future and it would be good to have tests so I am unlikely to break anything.

**Comment by JeremyRand** [comment]
> Can you add some tests that give at least 60% coverage of the new processing code in coins.py? I may need to refactor this or other parts of ElectrumX in the future and it would be good to have tests so I am unlikely to break anything.

Yes, I can do that, hopefully later today.

**Comment by JeremyRand** [comment]
Okay, so I think the only remaining code in this PR that isn't covered by tests is for functionality that also isn't tested for Bitcoin.  So, I think it's ready for review now.

**Pull request merged**
