### PR TITLE
Improve daemon JSON RPC compatibility

### PR DESCRIPTION
**Pull request by erasmospunk**
This commit adds an id counter as per the JSON RPC specs. Additionally
it is possible for a Daemon subclass to specify a custom transport
layer.

### CODE REVIEW

**Comment by kyuupichan** [comment]
John - can you explain what motivates these changes?

Also, is it possible to add some kind of tests for these?

**Comment by erasmospunk** [comment]
I was trying to make it work with [btcd](https://github.com/btcsuite/btcd) and noticed the missing id parameter and the inability to make ElectrumX work with HTTPS RPCs. This pull req solves some of the issues.

I would liked to add tests but it's not clear to me how to proceed in the case of the Daemon as it needs some kind of a mock server.

**Comment by kyuupichan** [comment]
OK thanks John; I'll push a slightly different version but that should be good enough for what you want.

**Comment by erasmospunk** [comment]
Looks good, thanks!

**Pull request closed without merging**
