### PR TITLE
Add Ravencoin support

### PR DESCRIPTION
**Pull request by DanielMazurFL4RE**

### CODE REVIEW

**Comment by kyuupichan** [comment]
This needs tests like other coins and to not break the build.

**Comment by DanielMazurFL4RE** [comment]
It breaks because of some whitechars left while pasting the code

**Comment by kyuupichan** [comment]
Will this be fixed or shall I close it?

**Comment by DanielMazurFL4RE** [comment]
> Will this be fixed or shall I close it?

There is some issues with whitespaces in python code, I will ask Ravencoin support if they like to fix it

**Comment by kyuupichan** [comment]
You seem to have a lot of merge issues; other coins are being touched

**Comment by DanielMazurFL4RE** [comment]
> You seem to have a lot of merge issues; other coins are being touched

Just add Ravencoin (coins.py, most bottom) class to your build, it works fine with Ravencoin, synchro going very fast due to small blockchain

**Pull request closed without merging**
