### PR TITLE
Add Terracoin Support (TRC)

### PR DESCRIPTION
**Pull request by TheSin-**
- Add Support for AuxPoW Masternode coins (AuxPoWDashElectrumX). This likely needs a rework as I had to copy the entire AuxPoW block and duplicate code is never a good idea.
- Add Terracoin as a coin
- Add Terracoin blocks to the tests

TODO:
This isn't for this pull as we do not support DIP3 yet. But eventually I'll need a way to combine the AuxPoW-tx with the dash-tx.

NOTES
The testnet and the electrum.terracoin.io node are being brought up and might not be running at the time this is viewed the other node is up and fully functional.

### CODE REVIEW

**Comment by kyuupichan** [comment]
Hi what's the status of this?

**Comment by TheSin-** [comment]
both servers are up and running this PR so I was hoping to get it accepted so I can try to get more nodes up, our wallet has been released https://terracoin.io/electrum/

Once I get us to DIP3 I'll work on an other PR to be able to fully combine AuxPoW and Dash, but for now it's working well as is.

**Comment by TheSin-** [comment]
Just curious why was this closed before being accepted?  I have been running it since the PR and have had no issues.

**Comment by kyuupichan** [comment]
I did the final release with multicoin support as 1.15

**Comment by TheSin-** [comment]
I saw that, but when I search the code on GitHub in that branch I can't find Terracoin so I assume it was not merged in?  Or am I missing something?

**Comment by kyuupichan** [comment]
There were conflicts so it wouldn't merge

**Comment by TheSin-** [comment]
oh originally when this was added there was not, I guess I'll rewrite it.  Thanks

**Pull request closed without merging**
