### PR TITLE
Added GZRO coin

### PR DESCRIPTION
**Pull request by MrNaif2018**
The title is self-descriptive.

### CODE REVIEW

**Comment by MrNaif2018** [comment]
@kyuupichan Could you please review and or/merge this pr? Thanks in advance.

**Comment by kyuupichan** [comment]
It needs tests like the other coins

**Comment by kyuupichan** [comment]
And it will fail the pycodestyle tests which didn't run for some reason

**Comment by MrNaif2018** [comment]
Is it fine to use black as formatter? I didn't use it as it would probably format the full code base.

**Comment by MrNaif2018** [comment]
@kyuupichan I have added tests, fixed code style and merge conflict. I think it is ready to merge.

**Comment by kyuupichan** [comment]
I would merge it but it involves a complete replacement of daemon.py for some reason.  Please do whatever your change is there as a change of a few lines.

**Comment by MrNaif2018** [comment]
it is because of merge conflicts, I resolved it manually. Actual change is small. Should I delete my fork and this pr and recreate it from latest master and insert those small changes?

**Comment by kyuupichan** [comment]
Sure that's fine with me.

**Comment by MrNaif2018** [comment]
Ok, will open a new one now.

**Pull request closed without merging**
