### PR TITLE
Coin fixes

### PR DESCRIPTION
**Pull request by erasmospunk**
- Fixed a crash when a coin didn't define the TX_COUNT_HEIGHT and IRC related variables
- Formatting and some fixes to coins.py

### CODE REVIEW

**Comment by erasmospunk** [comment]
Ops! Fixing...

**Comment by erasmospunk** [comment]
Hmm... seems that the test coverage decreased bit

**Comment by kyuupichan** [comment]
the coins.py changes are good.  Not so keen on the rest.  If the variable isn't there, how about a default in the base class, or raising an exception in env.py?

**Comment by kyuupichan** [comment]
What causes the crash if IRC is not set?  I missed that.

**Comment by kyuupichan** [comment]
Let me think about this a while

**Comment by kyuupichan** [comment]
I can't do 2 of 3.  Can you leave out the IRC; it seems wrong.  The other 2 are good

**Comment by kyuupichan** [comment]
I put 2/3 in 0.10.17; you didn't get back on the IRC part which seems wrong to me.

**Comment by erasmospunk** [comment]
@kyuupichan sorry missed the notifications.

Regarding the IRC, it is crashing [here](https://github.com/kyuupichan/electrumx/blob/master/server/irc.py#L34) for coins that didn't define IRC_CHANNEL (and IRC_PREFIX). The idea was that if IRC is not defined, then the IRC class should be created but I made a mistake in the `main_loop` function, the check should have been `if self.env.irc` as it was before.

**Comment by kyuupichan** [comment]
I see, thanks.  I'd rather we require all these to be set than fudge around them not being set.

So I'll do that.

**Pull request closed without merging**
