### PR TITLE
add AXE support (new class)

### PR DESCRIPTION
**Pull request by charlesrocket**

### CODE REVIEW

**Comment by kyuupichan** [comment]
You Daemon and Session classes seem identical to Dash's.  Why create new ones?

**Comment by charlesrocket** [comment]
@kyuupichan wanted to have some space to build on top in the future. should i convert with (Dash)? was about to add x11

**Comment by kyuupichan** [comment]
Well it seems nothing is new.  So either just reuse their classes, or if you want to keep your own, inherit theirs and add nothing.  Are you likely to want to add something that they won't have?  It seems your coin is a Dash clone.

**Comment by charlesrocket** [comment]
@kyuupichan you right, this is almost same code at this time, exact same for electrumx classes. i am cloning classes for future development, so we could pull this repo and build right on top of it. but looks like i need to add x11 for tests as well. so maybe it would be better to convert this PR to Dash classes. what would you suggest?

**Comment by charlesrocket** [comment]
noticed weird crash during wheel build on nightly. just tested on https://travis-ci.org/AXErunners/axe_hash could travis glitch? they went to maintenance after these commits

**Comment by erasmospunk** [comment]
This needs rebase and squashing everything in one commit.

**Comment by charlesrocket** [comment]
@erasmospunk guess it was a bad idea to go with one basket. any chance i could fix it with write access? 😞

**Comment by kyuupichan** [comment]
Not sure what's happened but your PR is a mess now (e.g. it's touching 13 files and has conflicts).  Can you fix and resubmit?

**Comment by charlesrocket** [comment]
@kyuupichan could you set tmp write access so i could have a look to fix it since there is another commits besides mines @erasmospunk requested complete squash, but i don't have write access to finish rebase and fix conflicts.

**Comment by kyuupichan** [comment]
It's all at your end, write access is not needed

**Comment by charlesrocket** [comment]
@kyuupichan you okay with resubmitting? can i go with dedicated branch to avoid same overlapping?

**Comment by kyuupichan** [comment]
Of course

**Comment by charlesrocket** [comment]
@kyuupichan got it, will resubmit

**Pull request closed without merging**
